dist: precise
sudo: false
language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.6
  - 7.0
  - 7.2

env:
  - WP_VERSION=latest

before_install:
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install --no-interaction

script:
  - WP_TESTS_DIR=/tmp/wordpress-tests-lib/ vendor/bin/phpunit -c phpunit.xml.dist
